/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksScrapeFdaRouteImport } from './routes/api/public/hooks/scrape-fda'
import { Route as ApiPublicHooksProcessPendingRouteImport } from './routes/api/public/hooks/process-pending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeFdaRoute = ApiPublicHooksScrapeFdaRouteImport.update({
  id: '/api/public/hooks/scrape-fda',
  path: '/api/public/hooks/scrape-fda',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessPendingRoute =
  ApiPublicHooksProcessPendingRouteImport.update({
    id: '/api/public/hooks/process-pending',
    path: '/api/public/hooks/process-pending',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/scrape-fda': typeof ApiPublicHooksScrapeFdaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/scrape-fda': typeof ApiPublicHooksScrapeFdaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/process-pending': typeof ApiPublicHooksProcessPendingRoute
  '/api/public/hooks/scrape-fda': typeof ApiPublicHooksScrapeFdaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/process-pending'
    | '/api/public/hooks/scrape-fda'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/process-pending' | '/api/public/hooks/scrape-fda'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/process-pending'
    | '/api/public/hooks/scrape-fda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksProcessPendingRoute: typeof ApiPublicHooksProcessPendingRoute
  ApiPublicHooksScrapeFdaRoute: typeof ApiPublicHooksScrapeFdaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-fda': {
      id: '/api/public/hooks/scrape-fda'
      path: '/api/public/hooks/scrape-fda'
      fullPath: '/api/public/hooks/scrape-fda'
      preLoaderRoute: typeof ApiPublicHooksScrapeFdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-pending': {
      id: '/api/public/hooks/process-pending'
      path: '/api/public/hooks/process-pending'
      fullPath: '/api/public/hooks/process-pending'
      preLoaderRoute: typeof ApiPublicHooksProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksProcessPendingRoute: ApiPublicHooksProcessPendingRoute,
  ApiPublicHooksScrapeFdaRoute: ApiPublicHooksScrapeFdaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
